version: '3'

services:
  frontend:
    build: ./
    image: repair-system-frontend
    ports:
      - 8080:80
    restart: on-failure

  backend:
    build: ../netunion-dnrs-backend
    image: repair-system-backend
    restart: on-failure
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=netunion_dnrs_visitor
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=netunion_dnrs

  postgres:
    image: postgres:alpine
    restart: on-failure
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=netunion_dnrs_visitor
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=netunion_dnrs

volumes:
  database: {}
